name: Deploy Django to EC2 via Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to EC2 with SSH
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          set -euxo pipefail

          # Loyihaga o‘tamiz
          cd ~/your_project_directory  # <--- BU YERDA loyihangiz joylashgan to‘liq papka yo‘lini yozing

          # Kodni yangilaymiz
          git fetch origin
          git reset --hard origin/master

          # Docker konteynerni qayta ishga tushiramiz
          sudo docker-compose down || true
          sudo docker-compose build --no-cache
          sudo docker-compose up -d
