name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/cloud.pem
        chmod 600 ~/.ssh/cloud.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/cloud.pem ubuntu@13.48.104.165 << 'EOF'
          cd ~/your_project_folder
          git pull origin main
          docker-compose down
          docker-compose up -d --build
        EOF
